name: General workflows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    name: Test Coverage
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - uses: actions/checkout@v2

      - name: Unit Test
        run: make test

      - name: Unit Test With Race
        run: make test_race

      - name: Get goverall
        run: go get github.com/mattn/goveralls

      - name: Upload coverage
        run: goveralls -coverprofile=coverage.out -repotoken ${{ secrets.GITHUB_TOKEN }}
